[workspace]
authors = ["kozo <kozoYang@outlook.com>"]
channels = ["rapidsai",
            "https://prefix.dev/meta-forge",
            "conda-forge"
]
name = "bootstraper"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
libc = { family = "glibc", version = "2.34" }
cuda = "12.7"

[dependencies]
seastar-dev = "*"
libboost-devel = ">=1.88.0,<2"
gnutls = ">=3.8.9,<4"
liburing = ">=2.9,<3"
libhwloc = ">=2.11.2,<3"
lksctp-tools = ">=1.0.21,<2"
systemtap = ">=5.3,<6"
libsctp-dev = ">=1.0.21,<2"
yaml-cpp = ">=0.8.0,<0.9"
lld = ">=20.1.5,<21"
cryptopp = ">=8.9.0,<9"
valgrind = ">=3.25.0,<4"
libnuma = ">=2.0.18,<3"
zlib = ">=1.3.1,<2"
lz4 = ">=4.4.4,<5"
ragel = ">=6.10,<7"
stow = ">=2.3.1,<3"
c-ares = ">=1.34.5,<2"
xfslibs-dev = ">=6.14.0,<7"
libprotobuf = "*"

[target.linux-64.dependencies]
cmake = "*"
make = "*"
cxx-compiler = "*"
c-compiler = "*"
rattler-build = "*"
rmm = "*"
cuda = "*"
ucxx = "*"
ucx = { channel = "conda-forge" }
sysroot_linux-64 = "2.34.*"
fmt = "*"
